NUM_CLASS: 10
OUTPUT_DIR: "train_dir/cifar10_hrnet18_1gpu"
SAVE_EPOCH_PERIOD: 10
PRINT_ITER_PERIOD: 5
TEST_EPOCH_PERIOD: 10

MODEL:
  NETWORK: ["hrnet",]
  NETWORK_STRIDE: []

SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 256
  BASE_LR: 0.1
  STEPS: [30, 60, 90]

TRAIN:
  TRANSFORMS:
    - ["RandomCrop", [["size", 32], ["padding", 4], ]]
    - ["RandomHorizontalFlip", []]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
TEST:
  BATCH_SIZE: 128
  TRANSFORMS:
    - ["Resize", [["size", 32], ]]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
