NUM_CLASS: 10
OUTPUT_DIR: "train_dir/config_cifar10_R20_1gpu"
SAVE_EPOCH_PERIOD: 10
PRINT_ITER_PERIOD: 5
TEST_EPOCH_PERIOD: 10

MODEL:
  NETWORK: ["resnet_cifar", [["block_name","BasicBlock"],["depth",20]],]
  NETWORK_STRIDE: [1, 1, 2, 2]

SOLVER:
  MAX_EPOCH: 200
  BATCH_SIZE: 128
  BASE_LR: 0.1
  STEPS: [100, 150]

TRAIN:
  TRANSFORMS:
    - ["RandomCrop", [["size", 32], ["padding", 4], ]]
    - ["RandomHorizontalFlip", []]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
TEST:
  BATCH_SIZE: 128
  TRANSFORMS:
    - ["Resize", [["size", 32], ]]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
